[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173

[functions]
  directory = "server"

[environment]
  NODE_VERSION = "18"

# SPA fallback so router paths work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
